import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";

export default async function SellerPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const seller = await prisma.user.findUnique({ where: { id }, select: { displayName: true, avatarUrl: true, createdAt: true, isBanned: true, listings: { where: { status: "PUBLISHED" }, orderBy: { publishedAt: "desc" }, include: { territory: { select: { name: true } }, location: { select: { name: true } }, images: { orderBy: { position: "asc" }, take: 1 } } } } });
  if (!seller || seller.isBanned) notFound();
  return <main className="searchPage"><header className="accountTopbar"><a className="brand" href="/"><span className="brandMark">AM</span><span>Antilles Market</span></a><a className="primaryButton" href="/deposer">+ Déposer</a></header><section className="searchResultsShell"><div className="sellerPublicHead"><div className="sellerAvatar">{seller.displayName.charAt(0).toUpperCase()}</div><div><span className="eyebrow">Profil vendeur</span><h1>{seller.displayName}</h1><p>Membre depuis {new Intl.DateTimeFormat("fr-FR", { month: "long", year: "numeric" }).format(seller.createdAt)} · {seller.listings.length} annonce{seller.listings.length !== 1 ? "s" : ""} active{seller.listings.length !== 1 ? "s" : ""}</p></div></div>{seller.listings.length ? <div className="resultsGrid">{seller.listings.map((listing) => <a className="resultCard" href={`/annonces/${listing.slug}`} key={listing.id}><div className="resultImage">{listing.images[0] ? <img src={listing.images[0].url} alt={listing.title} /> : <span>📷</span>}</div><div className="resultBody"><h2>{listing.title}</h2><strong>{listing.price ? new Intl.NumberFormat("fr-FR", { style: "currency", currency: listing.currency }).format(Number(listing.price)) : "Prix sur demande"}</strong><span>📍 {listing.location?.name ? `${listing.location.name}, ` : ""}{listing.territory.name}</span></div></a>)}</div> : <div className="emptyStateCard"><span>📦</span><h2>Aucune annonce active</h2><p>Ce vendeur n’a rien en vente actuellement.</p></div>}</section></main>;
}
